sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: p3uVjXHF8KBS3Nsm6cUai9FoPD9Z9ARpEYkNUErMmpBtIYLG9p8oTZM9fauSrA0kDJIidG2FuMllcPkn5CBjmmJC+p4r+a0ddmOA239Tx/cZ9VHwxuzJVw8gaGk80O5a9HXEy6kNfs6Uzpw6lW+RuUxFhLygKO161HB+3tgNochZCW+wei1pAlUxO1L67vJJ0/+uwni+3Q83QVW4TSiylfAhs346BOH4et4nsf1Zt61OLORPOl6m5sG5eXYIXXrenXVeiy3Kt/wYO+F2p4l/YerEppZ++zrDypgGnb6kSPgZeK7yZUVeqzn1QCUkauOJJ0KgKL2PcXU2EMRKPQMMrmKA5KoZHWE0npBp1JCldRprNXLsg7CiUR6sn3sPTt/F+5jibjkkVT1b3OSQkLVRykmRB8ZeuaCEPOmVPyplILfgF8DHqaHa7UwmMgrFTtC1PqhZo9iIA7HbcD3DkNYRQFPPbcJuEG0xlhXCl72Fc3KtspM+q0CG/VU37WL+NB087TSClQ5f9KWSTlKY6j+MwPm9j/APnwjtf/Uoy4ApeGb6rsLPzNTIUlXmqr5Kj7b6pBSPsLPZNmVx+OcfNF6HrA7h5zar3khLvxRkXZNGdlCK/ngw2v7dYNwKCrH2Rh5o4S1JaLSs3lZRNptWarVMicuj1DVqwBWDex0QLjc6VS8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cleopatra-Volume-07_5479
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy